[build]
  publish = "."
  command = "echo 'Build completed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/public/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200

