[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200
  force = false

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
