[build]
  publish = "."

# API redirects (highest priority)
[[redirects]]
  from = "/api/*"
  to = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200

# Static assets - serve from public directory (must come before catch-all)
[[redirects]]
  from = "/js/*"
  to = "/public/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/public/css/:splat"
  status = 200

# SPA fallback - serve app.html for all other requests (lowest priority)
[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
