[build]
  publish = "public"
  command = ""

# Backend proxy
[[redirects]]
  from = "/api/*"
  to   = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200
  force = true

# Serve login at the root
[[redirects]]
  from = "/"
  to   = "/index.html"
  status = 200

# Treat everything under /app/* as the SPA and serve app.html
[[redirects]]
  from = "/app/*"
  to   = "/app.html"
  status = 200