[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_VERSION = "18"

# API proxy to Render
[[redirects]]
  from = "/api/*"
  to = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (files that exist are served as-is; others rewrite to app.html)
[[redirects]]
  from = "/*"
  to = "/app.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Optional: cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"