[build]
  publish = "public"

[build.environment]
  VITE_SUPABASE_URL = "https://tugoaqoadsqbvgckkoqf.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1Z29hcW9hZHNxYnZnY2trb3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzkyMTAsImV4cCI6MjA3MjI1NTIxMH0.WU3b_pnTungZgPDcBhEVEzVugJYdIvMu_cE-zhGjvP4"
  VITE_RENDER_API_URL = "https://khizr-assistant-api.onrender.com"

# Redirect /env.js to Render backend
[[redirects]]
  from = "/env.js"
  to = "https://khizr-assistant-api.onrender.com/env.js"
  status = 200
  force = true

# Redirect API calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://khizr-assistant-api.onrender.com/api/:splat"
  status = 200

# SPA fallback - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
